image: gradle:8.3-jdk17

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - chmod +x gradlew
    - ./gradlew --build-cache --warning-mode all build publish
  artifacts:
    name: \"${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}:${CI_PIPELINE_ID}:${CI_JOB_NAME}\"
    paths:
      - 'build/libs/*.jar'
