name: Gradle Build & Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      env:
        MAVEN_LIVE_TOKEN: ${{ secrets.MAVEN_LIVE_TOKEN }}
        MAVEN_LIVE_USER: ${{ secrets.MAVEN_LIVE_USER }}
        MAVEN_LIVE_REPO: ${{ secrets.MAVEN_LIVE_REPO }}
        MAVEN_LIVE_URL: ${{ secrets.MAVEN_LIVE_URL }}
        MAVEN_DEV_TOKEN: ${{ secrets.MAVEN_DEV_TOKEN }}
        MAVEN_DEV_USER: ${{ secrets.MAVEN_DEV_USER }}
        MAVEN_DEV_REPO: ${{ secrets.MAVEN_DEV_REPO }}
        MAVEN_DEV_URL: ${{ secrets.MAVEN_DEV_URL }}
      run: ./gradlew --build-cache --warning-mode all build publish